// One-time generator for catalog/source.xlsx — the demo catalog's editable
// source. After this runs, source.xlsx is the artifact people actually edit;
// this script just bootstraps its first 42 rows so the file isn't hand-typed
// into a spreadsheet by hand for a hackathon demo.
import XLSX from "xlsx";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const HEADERS = [
  "id", "category", "name", "brand", "priceCents", "finish",
  "width", "depth", "height", "clearanceFront", "clearanceSide",
  "gpf", "gpm", "installComplexity", "styleTags",
  "themeMinimalistModern", "themeClassicLuxury", "themeJapaneseZen",
  "finishFamily", "imageUrl",
];

function row(fields) {
  const out = {};
  for (const h of HEADERS) out[h] = fields[h] ?? "";
  return out;
}

const rows = [
  // --- toilets (8) ---
  row({ id: "kt-santorini", category: "toilet", name: "Santorini Comfort Height", brand: "Kohler", priceCents: 42900, finish: "white", width: 15.5, depth: 27.75, height: 30.5, clearanceFront: 21, clearanceSide: 15, gpf: 1.28, installComplexity: "standard", styleTags: "comfort-height;elongated", themeMinimalistModern: 0.8, themeClassicLuxury: 0.3, themeJapaneseZen: 0.5, finishFamily: "kohler-white-standard" }),
  row({ id: "kt-veil", category: "toilet", name: "Veil Wall-Hung Toilet", brand: "Kohler", priceCents: 189900, finish: "white", width: 14.5, depth: 21.5, height: 14, clearanceFront: 21, clearanceSide: 15, gpf: 1.0, installComplexity: "specialist", styleTags: "wall-hung;concealed-tank;low-profile", themeMinimalistModern: 0.95, themeClassicLuxury: 0.2, themeJapaneseZen: 0.7, finishFamily: "kohler-white-standard" }),
  row({ id: "kt-memoirs", category: "toilet", name: "Memoirs Classic", brand: "Kohler", priceCents: 61200, finish: "white", width: 16.5, depth: 30, height: 31, clearanceFront: 21, clearanceSide: 15, gpf: 1.28, installComplexity: "standard", styleTags: "elongated;traditional;carved-details", themeMinimalistModern: 0.2, themeClassicLuxury: 0.9, themeJapaneseZen: 0.3, finishFamily: "kohler-white-standard" }),
  row({ id: "kt-cimarron", category: "toilet", name: "Cimarron Comfort Height", brand: "Kohler", priceCents: 34900, finish: "white", width: 16.375, depth: 28.75, height: 30.25, clearanceFront: 21, clearanceSide: 15, gpf: 1.28, installComplexity: "standard", styleTags: "elongated;comfort-height", themeMinimalistModern: 0.5, themeClassicLuxury: 0.6, themeJapaneseZen: 0.4, finishFamily: "kohler-white-standard" }),
  row({ id: "kt-sansouci", category: "toilet", name: "San Souci One-Piece", brand: "Kohler", priceCents: 45500, finish: "white", width: 16.5, depth: 29, height: 27, clearanceFront: 21, clearanceSide: 15, gpf: 1.28, installComplexity: "standard", styleTags: "one-piece;low-profile-tank", themeMinimalistModern: 0.6, themeClassicLuxury: 0.4, themeJapaneseZen: 0.5, finishFamily: "kohler-white-standard" }),
  row({ id: "kt-purist-hatbox", category: "toilet", name: "Purist Hatbox", brand: "Kohler", priceCents: 79500, finish: "white", width: 15.25, depth: 27, height: 22.75, clearanceFront: 21, clearanceSide: 15, gpf: 1.28, installComplexity: "standard", styleTags: "round-tank;hatbox;sculptural", themeMinimalistModern: 0.7, themeClassicLuxury: 0.5, themeJapaneseZen: 0.8, finishFamily: "kohler-white-standard" }),
  row({ id: "kt-highline", category: "toilet", name: "Highline Classic", brand: "Kohler", priceCents: 29900, finish: "white", width: 15.25, depth: 28.5, height: 29.75, clearanceFront: 21, clearanceSide: 15, gpf: 1.28, installComplexity: "drop-in", styleTags: "elongated;budget", themeMinimalistModern: 0.4, themeClassicLuxury: 0.5, themeJapaneseZen: 0.3, finishFamily: "kohler-white-standard" }),
  row({ id: "kt-persuade", category: "toilet", name: "Persuade Curv", brand: "Kohler", priceCents: 52000, finish: "white", width: 16.5, depth: 29.75, height: 29.5, clearanceFront: 21, clearanceSide: 15, gpf: 1.28, installComplexity: "standard", styleTags: "curved-silhouette;elongated", themeMinimalistModern: 0.55, themeClassicLuxury: 0.6, themeJapaneseZen: 0.4, finishFamily: "kohler-white-standard" }),

  // --- vanities (9) ---
  row({ id: "kv-poplin30", category: "vanity", name: "Poplin 30in Single Vanity", brand: "Kohler", priceCents: 124000, finish: "matte-black", width: 30, depth: 21.5, height: 34.5, installComplexity: "standard", styleTags: "floating;matte-black-cabinet;single-bowl", themeMinimalistModern: 0.85, themeClassicLuxury: 0.3, themeJapaneseZen: 0.6, finishFamily: "kohler-matte-black-hardware" }),
  row({ id: "kv-damask48", category: "vanity", name: "Damask 48in Double Vanity", brand: "Kohler", priceCents: 289000, finish: "brushed-nickel", width: 48, depth: 22, height: 35, installComplexity: "standard", styleTags: "double-bowl;shaker-cabinet;white-oak", themeMinimalistModern: 0.3, themeClassicLuxury: 0.9, themeJapaneseZen: 0.3, finishFamily: "kohler-nickel-hardware" }),
  row({ id: "kv-jute24", category: "vanity", name: "Jute 24in Vanity", brand: "Kohler", priceCents: 98000, finish: "brushed-gold", width: 24, depth: 19, height: 34, installComplexity: "standard", styleTags: "walnut-veneer;floating;compact", themeMinimalistModern: 0.7, themeClassicLuxury: 0.4, themeJapaneseZen: 0.75, finishFamily: "kohler-gold-hardware" }),
  row({ id: "kv-verdera36", category: "vanity", name: "Verdera 36in Vanity", brand: "Kohler", priceCents: 156000, finish: "chrome", width: 36, depth: 21, height: 34.5, installComplexity: "standard", styleTags: "white-lacquer;soft-close;minimal", themeMinimalistModern: 0.8, themeClassicLuxury: 0.35, themeJapaneseZen: 0.55, finishFamily: "kohler-chrome-hardware" }),
  row({ id: "kv-tresham30", category: "vanity", name: "Tresham 30in Vanity", brand: "Kohler", priceCents: 89000, finish: "oil-rubbed-bronze", width: 30, depth: 22, height: 34, installComplexity: "standard", styleTags: "traditional;raised-panel;cherry-finish", themeMinimalistModern: 0.2, themeClassicLuxury: 0.85, themeJapaneseZen: 0.3, finishFamily: "kohler-bronze-hardware" }),
  row({ id: "kv-maxstow-corner", category: "vanity", name: "Maxstow Corner Vanity", brand: "Kohler", priceCents: 76000, finish: "brushed-nickel", width: 22, depth: 22, height: 33, installComplexity: "standard", styleTags: "corner-fit;compact;small-bath", themeMinimalistModern: 0.6, themeClassicLuxury: 0.4, themeJapaneseZen: 0.5, finishFamily: "kohler-nickel-hardware" }),
  row({ id: "kv-derwent48", category: "vanity", name: "Derwent 48in Double Vanity", brand: "Kohler", priceCents: 245000, finish: "matte-black", width: 48, depth: 21.5, height: 34.5, installComplexity: "standard", styleTags: "double-bowl;matte-black-cabinet;linear-pulls", themeMinimalistModern: 0.9, themeClassicLuxury: 0.25, themeJapaneseZen: 0.6, finishFamily: "kohler-matte-black-hardware" }),
  row({ id: "kv-linear-teak24", category: "vanity", name: "Linear Teak 24in Vanity", brand: "Kohler", priceCents: 112000, finish: "stainless-steel", width: 24, depth: 20, height: 32, installComplexity: "standard", styleTags: "teak;wall-mounted;spa-style", themeMinimalistModern: 0.75, themeClassicLuxury: 0.3, themeJapaneseZen: 0.9, finishFamily: "kohler-steel-hardware" }),
  row({ id: "kv-ainsley30-lowered", category: "vanity", name: "Ainsley 30in Lowered-ADA Vanity", brand: "Kohler", priceCents: 99000, finish: "brushed-nickel", width: 30, depth: 21, height: 30, installComplexity: "standard", styleTags: "ada-height;accessible;knee-clearance", themeMinimalistModern: 0.5, themeClassicLuxury: 0.5, themeJapaneseZen: 0.5, finishFamily: "kohler-nickel-hardware" }),

  // --- faucets (9) ---
  row({ id: "kf-purist-single", category: "faucet", name: "Purist Single-Handle Faucet", brand: "Kohler", priceCents: 32900, finish: "chrome", width: 2, depth: 6, height: 9, gpm: 1.2, installComplexity: "drop-in", styleTags: "single-handle;minimal;widespread-optional", themeMinimalistModern: 0.85, themeClassicLuxury: 0.3, themeJapaneseZen: 0.6, finishFamily: "kohler-chrome-hardware" }),
  row({ id: "kf-artifacts-bridge", category: "faucet", name: "Artifacts Bridge Faucet", brand: "Kohler", priceCents: 68500, finish: "brushed-gold", width: 3, depth: 8, height: 10, gpm: 1.5, installComplexity: "standard", styleTags: "bridge;traditional;cross-handles", themeMinimalistModern: 0.2, themeClassicLuxury: 0.9, themeJapaneseZen: 0.3, finishFamily: "kohler-gold-hardware" }),
  row({ id: "kf-composed-wall", category: "faucet", name: "Composed Wall-Mount Faucet", brand: "Kohler", priceCents: 74500, finish: "matte-black", width: 2, depth: 9, height: 7, gpm: 1.2, installComplexity: "specialist", styleTags: "wall-mount;minimal;low-profile", themeMinimalistModern: 0.9, themeClassicLuxury: 0.2, themeJapaneseZen: 0.75, finishFamily: "kohler-matte-black-hardware" }),
  row({ id: "kf-forte-single", category: "faucet", name: "Forte Single-Handle Faucet", brand: "Kohler", priceCents: 18900, finish: "chrome", width: 2, depth: 6.5, height: 8, gpm: 1.5, installComplexity: "drop-in", styleTags: "single-handle;value", themeMinimalistModern: 0.5, themeClassicLuxury: 0.5, themeJapaneseZen: 0.4, finishFamily: "kohler-chrome-hardware" }),
  row({ id: "kf-margaux-single", category: "faucet", name: "Margaux Single-Handle Faucet", brand: "Kohler", priceCents: 45500, finish: "oil-rubbed-bronze", width: 2.5, depth: 7, height: 11, gpm: 1.5, installComplexity: "standard", styleTags: "traditional;high-arc", themeMinimalistModern: 0.25, themeClassicLuxury: 0.85, themeJapaneseZen: 0.35, finishFamily: "kohler-bronze-hardware" }),
  row({ id: "kf-avid-single", category: "faucet", name: "Avid Single-Handle Faucet", brand: "Kohler", priceCents: 22900, finish: "brushed-nickel", width: 2, depth: 6, height: 8.5, gpm: 1.5, installComplexity: "drop-in", styleTags: "single-handle;transitional", themeMinimalistModern: 0.55, themeClassicLuxury: 0.55, themeJapaneseZen: 0.45, finishFamily: "kohler-nickel-hardware" }),
  row({ id: "kf-tone-vessel", category: "faucet", name: "Tone Vessel Faucet", brand: "Kohler", priceCents: 39900, finish: "brushed-gold", width: 2, depth: 6, height: 12, gpm: 1.2, installComplexity: "standard", styleTags: "vessel-height;minimal;sculptural", themeMinimalistModern: 0.8, themeClassicLuxury: 0.35, themeJapaneseZen: 0.8, finishFamily: "kohler-gold-hardware" }),
  row({ id: "kf-castia-single", category: "faucet", name: "Castia Single-Handle Faucet", brand: "Kohler", priceCents: 27500, finish: "stainless-steel", width: 2, depth: 6.25, height: 8, gpm: 1.5, installComplexity: "drop-in", styleTags: "single-handle;contemporary", themeMinimalistModern: 0.65, themeClassicLuxury: 0.4, themeJapaneseZen: 0.55, finishFamily: "kohler-steel-hardware" }),
  row({ id: "kf-purist-wide", category: "faucet", name: "Purist Widespread Faucet", brand: "Kohler", priceCents: 58500, finish: "chrome", width: 8, depth: 6, height: 6.5, gpm: 1.2, installComplexity: "standard", styleTags: "widespread;minimal;architectural", themeMinimalistModern: 0.9, themeClassicLuxury: 0.4, themeJapaneseZen: 0.65, finishFamily: "kohler-chrome-hardware" }),

  // --- showers (8) ---
  row({ id: "ks-anthem-system", category: "shower", name: "Anthem Digital Shower System", brand: "Kohler", priceCents: 189000, finish: "matte-black", width: 8, depth: 4, height: 48, gpm: 2.0, installComplexity: "specialist", styleTags: "digital-control;multi-outlet;curbless-compatible", themeMinimalistModern: 0.9, themeClassicLuxury: 0.3, themeJapaneseZen: 0.6, finishFamily: "kohler-matte-black-hardware" }),
  row({ id: "ks-purist-panel", category: "shower", name: "Purist Shower Panel", brand: "Kohler", priceCents: 145000, finish: "chrome", width: 10, depth: 4, height: 48, gpm: 1.75, installComplexity: "standard", styleTags: "rain-head;handshower;minimal", themeMinimalistModern: 0.85, themeClassicLuxury: 0.3, themeJapaneseZen: 0.65, finishFamily: "kohler-chrome-hardware" }),
  row({ id: "ks-artifacts-thermostatic", category: "shower", name: "Artifacts Thermostatic Valve Trim", brand: "Kohler", priceCents: 98500, finish: "brushed-gold", width: 6, depth: 4, height: 8, gpm: 2.0, installComplexity: "standard", styleTags: "thermostatic;traditional;cross-handle", themeMinimalistModern: 0.2, themeClassicLuxury: 0.9, themeJapaneseZen: 0.3, finishFamily: "kohler-gold-hardware" }),
  row({ id: "ks-forte-multifunction", category: "shower", name: "Forte Multifunction Shower Kit", brand: "Kohler", priceCents: 32900, finish: "chrome", width: 8, depth: 3, height: 24, gpm: 2.0, installComplexity: "drop-in", styleTags: "value;multifunction-head", themeMinimalistModern: 0.5, themeClassicLuxury: 0.5, themeJapaneseZen: 0.4, finishFamily: "kohler-chrome-hardware" }),
  row({ id: "ks-statement-curbless", category: "shower", name: "Statement Curbless Shower Base", brand: "Kohler", priceCents: 156000, finish: "white", width: 60, depth: 32, height: 4, installComplexity: "specialist", styleTags: "curbless;ada;linear-drain", themeMinimalistModern: 0.7, themeClassicLuxury: 0.3, themeJapaneseZen: 0.6, finishFamily: "kohler-white-standard" }),
  row({ id: "ks-composed-rain", category: "shower", name: "Composed Rain Head System", brand: "Kohler", priceCents: 112000, finish: "matte-black", width: 12, depth: 12, height: 2, gpm: 1.75, installComplexity: "standard", styleTags: "rain-head;ceiling-mount;minimal", themeMinimalistModern: 0.9, themeClassicLuxury: 0.25, themeJapaneseZen: 0.75, finishFamily: "kohler-matte-black-hardware" }),
  row({ id: "ks-margaux-handshower", category: "shower", name: "Margaux Handshower Column", brand: "Kohler", priceCents: 87500, finish: "oil-rubbed-bronze", width: 4, depth: 4, height: 48, gpm: 2.0, installComplexity: "standard", styleTags: "traditional;column;handshower", themeMinimalistModern: 0.25, themeClassicLuxury: 0.85, themeJapaneseZen: 0.35, finishFamily: "kohler-bronze-hardware" }),
  row({ id: "ks-avid-shower-kit", category: "shower", name: "Avid Shower Trim Kit", brand: "Kohler", priceCents: 41500, finish: "brushed-nickel", width: 7, depth: 3, height: 22, gpm: 2.0, installComplexity: "standard", styleTags: "transitional;multifunction-head", themeMinimalistModern: 0.55, themeClassicLuxury: 0.55, themeJapaneseZen: 0.45, finishFamily: "kohler-nickel-hardware" }),

  // --- lighting (8) ---
  row({ id: "kl-purist-sconce", category: "lighting", name: "Purist Vanity Sconce", brand: "Kohler", priceCents: 24500, finish: "chrome", width: 5, depth: 5, height: 14, installComplexity: "drop-in", styleTags: "sconce;minimal;linear-glass", themeMinimalistModern: 0.85, themeClassicLuxury: 0.35, themeJapaneseZen: 0.6, finishFamily: "kohler-chrome-hardware" }),
  row({ id: "kl-artifacts-pendant", category: "lighting", name: "Artifacts Pendant", brand: "Kohler", priceCents: 38500, finish: "brushed-gold", width: 8, depth: 8, height: 12, installComplexity: "standard", styleTags: "pendant;traditional;glass-shade", themeMinimalistModern: 0.25, themeClassicLuxury: 0.9, themeJapaneseZen: 0.35, finishFamily: "kohler-gold-hardware" }),
  row({ id: "kl-composed-bar", category: "lighting", name: "Composed LED Vanity Bar", brand: "Kohler", priceCents: 32900, finish: "matte-black", width: 24, depth: 4, height: 4, installComplexity: "standard", styleTags: "led;bar-light;minimal", themeMinimalistModern: 0.9, themeClassicLuxury: 0.25, themeJapaneseZen: 0.65, finishFamily: "kohler-matte-black-hardware" }),
  row({ id: "kl-forte-flushmount", category: "lighting", name: "Forte Flush Mount", brand: "Kohler", priceCents: 12900, finish: "white", width: 11, depth: 11, height: 5, installComplexity: "drop-in", styleTags: "value;flush-mount", themeMinimalistModern: 0.5, themeClassicLuxury: 0.5, themeJapaneseZen: 0.4, finishFamily: "kohler-white-standard" }),
  row({ id: "kl-tone-backlit-mirror", category: "lighting", name: "Tone Backlit LED Mirror", brand: "Kohler", priceCents: 68500, finish: "stainless-steel", width: 30, depth: 1.5, height: 36, installComplexity: "standard", styleTags: "backlit;anti-fog;mirror-light", themeMinimalistModern: 0.8, themeClassicLuxury: 0.3, themeJapaneseZen: 0.7, finishFamily: "kohler-steel-hardware" }),
  row({ id: "kl-margaux-sconce", category: "lighting", name: "Margaux Wall Sconce", brand: "Kohler", priceCents: 29500, finish: "oil-rubbed-bronze", width: 5, depth: 6, height: 16, installComplexity: "standard", styleTags: "traditional;candlestick-style", themeMinimalistModern: 0.2, themeClassicLuxury: 0.85, themeJapaneseZen: 0.3, finishFamily: "kohler-bronze-hardware" }),
  row({ id: "kl-verdera-cabinet-light", category: "lighting", name: "Verdera Lighted Medicine Cabinet", brand: "Kohler", priceCents: 89500, finish: "brushed-nickel", width: 30, depth: 5, height: 33, installComplexity: "standard", styleTags: "storage;backlit;defogger", themeMinimalistModern: 0.75, themeClassicLuxury: 0.4, themeJapaneseZen: 0.55, finishFamily: "kohler-nickel-hardware" }),
  row({ id: "kl-zen-pendant-linear", category: "lighting", name: "Zen Linear Pendant", brand: "Kohler", priceCents: 45500, finish: "brushed-gold", width: 36, depth: 4, height: 5, installComplexity: "standard", styleTags: "linear;paper-lantern-inspired;soft-glow", themeMinimalistModern: 0.5, themeClassicLuxury: 0.3, themeJapaneseZen: 0.95, finishFamily: "kohler-gold-hardware" }),
];

const sheet = XLSX.utils.json_to_sheet(rows, { header: HEADERS });
const book = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(book, sheet, "catalog");

const outPath = path.join(__dirname, "source.xlsx");
XLSX.writeFile(book, outPath);
console.log(`Wrote ${rows.length} rows to ${outPath}`);
